import React, { useState } from 'react'
import { motion } from 'framer-motion'
import { Beaker, Sparkles, Target, Zap, Globe, MoreHorizontal, ThumbsUp, MessageCircle, Share2, ExternalLink, Loader2 } from 'lucide-react'

import { API_BASE_URL } from '../services/api'

// Helper to create a consistent seed for Pollinations from the prompt
const hashString = (str) => {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash) + str.charCodeAt(i);
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
}

function AdMockup({ testData, type, label, visualPrompt }) {
  const isA = type === 'A'
  const accentColor = isA ? 'blue' : 'amber'
  const AccentIcon = isA ? Target : Zap
  const brandName = "AdMind"
  
  const [retryCount, setRetryCount] = React.useState(0);
  const [isLoading, setIsLoading] = React.useState(true);

  return (
    <div className={`relative flex flex-col rounded-2xl border-2 border-${accentColor}-500/30 bg-slate-900 overflow-hidden group hover:border-${accentColor}-500/60 transition-colors shadow-lg`}>
      {/* Top Banner */}
      <div className={`absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-${accentColor}-400 to-${accentColor}-600`} />
      
      {/* Ad Header */}
      <div className="flex items-center justify-between p-4 border-b border-white/5 bg-white/5">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-full bg-gradient-to-br from-slate-700 to-slate-900 border border-white/10 shadow-inner flex items-center justify-center p-1">
            <div className="h-full w-full rounded-full bg-slate-800 flex items-center justify-center text-xs font-black text-slate-400">
              {brandName.charAt(0)}
            </div>
          </div>
          <div>
            <h4 className="text-[15px] font-bold text-white tracking-tight leading-none mb-1">{brandName}</h4>
            <div className="flex items-center gap-1.5 text-[11px] text-slate-400 font-medium">
              <span>Sponsored</span>
              <span className="w-1 h-1 rounded-full bg-slate-600" />
              <Globe size={10} />
            </div>
          </div>
        </div>
        <button className="text-slate-500 hover:text-slate-300 transition-colors">
          <MoreHorizontal size={20} />
        </button>
      </div>

      {/* Ad Text */}
      <div className="p-5 flex-1 relative">
        <p className="text-[15px] text-slate-200 whitespace-pre-wrap leading-relaxed font-medium">
          {testData?.description}
        </p>
      </div>

      {/* Ad Image Creative (Generated by Backend Fallback Manager) */}
      {visualPrompt && (
        <div className="w-full aspect-[4/3] overflow-hidden border-y border-white/5 bg-slate-950 relative group">
          {isLoading && (
            <div className="absolute inset-0 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm z-10">
              <Loader2 className="w-8 h-8 text-purple-500 animate-spin" />
            </div>
          )}
          <img 
            key={`img-${retryCount}`}
            src={`${API_BASE_URL}/workspaces/images/generate?prompt=${encodeURIComponent(visualPrompt)}&seed=${Math.abs(hashString(visualPrompt + type)) + retryCount}`} 
            alt="AI Generated Ad Creative" 
            loading="lazy"
            className={`w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 ${isLoading ? 'opacity-0' : 'opacity-100'}`}
            onError={(e) => {
              setIsLoading(false);
              e.target.style.display = 'none';
              e.target.nextSibling.style.display = 'flex';
            }}
            onLoad={(e) => {
              setIsLoading(false);
              e.target.style.display = 'block';
              if (e.target.nextSibling) {
                e.target.nextSibling.style.display = 'none';
              }
            }}
          />
          {/* Fallback gradient if Pollinations rate limits or fails */}
          <div className="hidden absolute inset-0 bg-gradient-to-br from-slate-800 to-slate-900 items-center justify-center flex-col text-slate-500 p-6 text-center">
             <div className="mb-2 font-semibold">Pollinations API Rate Limited</div>
             <div className="text-xs mb-3">The free image generation API received too many requests at once.</div>
             <button 
               onClick={() => setRetryCount(c => c + 1)}
               className="text-[11px] bg-slate-700 hover:bg-slate-600 text-white px-3 py-1.5 rounded-lg transition-colors border border-slate-600"
             >
               Retry Image
             </button>
          </div>
        </div>
      )}

      {/* Headline & CTA */}
      <div className="p-4 bg-slate-800/80 flex items-center justify-between gap-4">
        <div className="flex-1">
          <p className="text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1">
            {testData?.angle || 'Performance Angle'}
          </p>
          <h3 className="text-base font-bold text-white leading-tight">
            {testData?.headline || 'Boost Your Campaign ROI Today'}
          </h3>
        </div>
        <button className={`shrink-0 bg-white/10 hover:bg-white/20 transition-colors text-white text-xs font-bold px-4 py-2 rounded-lg border border-white/10`}>
          Learn More
        </button>
      </div>

      {/* Social Actions (Mock) */}
      <div className="px-4 py-3 flex items-center gap-6 border-t border-white/5 text-slate-400">
        <div className="flex items-center gap-1.5 hover:text-slate-200 cursor-pointer transition-colors"><ThumbsUp size={16} /> <span className="text-xs font-medium">Like</span></div>
        <div className="flex items-center gap-1.5 hover:text-slate-200 cursor-pointer transition-colors"><MessageCircle size={16} /> <span className="text-xs font-medium">Comment</span></div>
        <div className="flex items-center gap-1.5 hover:text-slate-200 cursor-pointer transition-colors"><Share2 size={16} /> <span className="text-xs font-medium">Share</span></div>
      </div>
    </div>
  )
}

export default function CopyResults({ copy }) {
  if (!copy) return null

  return (
    <motion.section 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="py-4"
    >
      <div className="glass-panel rounded-3xl p-6 lg:p-8 border-white/5 relative overflow-hidden">
        {/* Subtle background glow */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-purple-500/5 rounded-full blur-[100px] pointer-events-none" />

        <div className="flex items-center gap-4 mb-8">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-purple-500/20 text-purple-400 shadow-inner">
            <Beaker size={24} aria-hidden="true" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white tracking-tight">A/B Test Frameworks</h2>
            <p className="text-slate-400 text-sm mt-0.5">AI-generated structured creative tests</p>
          </div>
        </div>

        <motion.div 
          initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.1 }}
          className="rounded-2xl bg-gradient-to-r from-purple-900/40 to-slate-900/40 border border-purple-500/20 p-6 text-sm leading-relaxed text-purple-100 mb-12 shadow-[0_0_15px_rgba(168,85,247,0.15)] backdrop-blur-sm"
        >
          <span className="font-bold mr-2 text-purple-400 uppercase tracking-wider text-xs border border-purple-500/30 bg-purple-500/10 px-2 py-1 rounded">Copywriter Summary</span>
          <span className="ml-2 block mt-3 text-[15px]">{copy.summary}</span>
        </motion.div>

        <div className="grid gap-16">
          {copy.variants.map((variant, index) => (
            <motion.article
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 * index }}
              key={`${variant.keyword}-ab`}
              className="relative"
            >
              {/* Keyword header */}
              <div className="mb-8 flex flex-col items-center text-center">
                <span className="inline-block rounded-xl bg-gradient-to-br from-purple-500/20 to-pink-500/20 px-6 py-2 text-lg font-black text-white shadow-[0_0_15px_rgba(168,85,247,0.2)] border border-purple-500/30 tracking-wide">
                  {variant.keyword}
                </span>
                <span className="text-sm font-bold text-slate-400 mt-3 uppercase tracking-widest flex items-center gap-2">
                  <ExternalLink size={14} /> {variant.campaign_name}
                </span>
              </div>

              {/* Side-by-side A/B tests */}
              <div className="grid lg:grid-cols-2 gap-8 relative px-4 lg:px-0">
                
                {/* VS Badge in the middle */}
                <div className="hidden lg:flex absolute top-[40%] left-1/2 -translate-x-1/2 w-12 h-12 rounded-full bg-slate-900 border-4 border-slate-800 items-center justify-center z-10 shadow-[0_0_20px_rgba(0,0,0,0.8)]">
                  <span className="text-[12px] font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-amber-400">VS</span>
                </div>

                {/* Test A Mockup */}
                <AdMockup testData={variant.test_a} type="A" label={variant.test_a?.label || 'Variation A'} visualPrompt={variant.visual_prompt} />

                {/* Test B Mockup */}
                <AdMockup testData={variant.test_b} type="B" label={variant.test_b?.label || 'Variation B'} visualPrompt={variant.visual_prompt} />
              </div>

              {/* Test rationale */}
              <div className="mt-8 mx-auto max-w-3xl flex items-start gap-4 rounded-2xl bg-gradient-to-r from-slate-900/80 to-slate-800/80 p-6 border border-white/10 shadow-lg">
                <div className="p-2 bg-purple-500/20 rounded-xl shadow-[0_0_10px_rgba(168,85,247,0.2)] border border-purple-500/30">
                  <Sparkles size={20} className="text-purple-400" aria-hidden="true" />
                </div>
                <div className="flex-1">
                  <h4 className="font-bold text-white text-base mb-1">Strategic Rationale</h4>
                  <p className="text-[15px] leading-relaxed text-slate-300">
                    {variant.test_rationale || variant.improvement_reason || ''}
                  </p>
                </div>
              </div>
              
              {/* Divider between variants (except last) */}
              {index < copy.variants.length - 1 && (
                <div className="h-px w-full bg-gradient-to-r from-transparent via-white/10 to-transparent mt-16" />
              )}
            </motion.article>
          ))}
        </div>
      </div>
    </motion.section>
  )
}
